In [1]:
import numpy as np 
a = np.array([1,2,3]) 
print(a)

[1 2 3]


#### more than one dimensions 

In [2]:
a = np.array([[1, 2], [3, 4]]) 
print (a)

[[1 2]
 [3 4]]


#### minimum dimensions

In [3]:
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print (a)

[[1 2 3 4 5]]


#### dtype parameter 

In [4]:
a = np.array([1, 2, 3], dtype = complex) 
print(a)

[1.+0.j 2.+0.j 3.+0.j]


#### using array-scalar type 

In [5]:
dt=np.dtype(np.int32)
print(dt)

int32


#### int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc. 

In [6]:
dt=np.dtype('i8')
print(dt)

int64



#### using endian notation 

In [7]:
dt=np.dtype('>i8')
print(dt)

>i8


### The following examples show the use of structured data type. Here, the field name and the corresponding scalar data type is to be declared.

In [8]:
dt=np.dtype([('age',np.int8)])
print(dt)

[('age', 'i1')]


#### now apply it to ndarray object

In [9]:
a=np.array([(10,),(20,),(30,)],dtype=dt)
print(a)

[(10,) (20,) (30,)]


#### File name can be used to access the content of the column

In [10]:
print(a['age'])

[10 20 30]


### The following examples define a structured data type called student with a string field 'name', an integer field 'age' and a float field 'marks'. This dtype is applied to ndarray object.

In [11]:
student=np.dtype([('name','S20'),('age','i2'),('marks','f4')])
print(student)

[('name', 'S20'), ('age', '<i2'), ('marks', '<f4')]


#### lets try understand what 'S20' and 'f4'

dt=np.dtype('S20')
print(dt)

# string defined as S20

In [12]:
dt=np.dtype('f4')
print(dt)

float32


In [13]:
a=np.array([('Rahul', 49,0.001),('Priyanka', 46,0.090),('varba',50,0.0123)], dtype=student)
print(a)

[(b'Rahul', 49, 0.001 ) (b'Priyanka', 46, 0.09  ) (b'varba', 50, 0.0123)]


### In this chapter, we will discuss the various array attributes of NumPy.

In [14]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


#### Above represents two rows and three columns

#### Now resize this to (3,2) below

In [15]:
a.shape=(3,2)
print('Shape: ',a.shape)
print('Reshaped to 3 rows and 2 columns as below\n',a)

Shape:  (3, 2)
Reshaped to 3 rows and 2 columns as below
 [[1 2]
 [3 4]
 [5 6]]


#### This can be done with numpy reshape back to original (2,3)

In [16]:
b=a.reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]


## ndarray.ndim
#### This array attribute returns the number of array dimensions.

In [18]:
# an array of evenly spaced numbers in One dimensional array
a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


#### now reshape 1d array 3d

In [24]:
b=a.reshape(2,4,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
