## NumPy - Array Creation Routines

#### numpy.empty

Create an uninitialized array of specified shape and dtype

In [3]:
# numpy.empty(shape, dtype = float, order = 'C')
# Shape: Shape of an empty array in int or tuple of int
# Dtype: Desired output data type. Optional
# Order: 'C' for C-style row-major array, 'F' for FORTRAN style column-major array


In [4]:
import numpy as np 
x = np.empty([3,2], dtype = int) 
print (x)

[[0 0]
 [0 0]
 [0 0]]


In [5]:
# numpy.zeros(shape, dtype = float, order = 'C')
x = np.zeros([3,2], dtype=float)
print(x)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [6]:
# numpy.ones(shape, dtype = None, order = 'C')
x = np.ones(3)
print(x)
# Default Dtype is Float here

[1. 1. 1.]


In [8]:
x=np.ones([2,1], dtype=int)
print(x)

[[1]
 [1]]


# NumPy - Array From Existing Data

### numpy.asarray

This is similar to numpy.array it has fewer parameters compared to numpy.array and useful for converting python sequence into ndarry

In [9]:
#numpy.asarray(a, dtype = None, order = None)

# a : Input data in any form such as list, list of tuples, tuples, tuple of tuples or tuple of lists

In [10]:
# convert list to ndarray 
x = [1,2,3]
a=np.asarray(x)
print(a)

[1 2 3]


In [11]:
# dtype is set
x = [1,2,3]
a = np.asarray(x, dtype = float) 
print (a)

[1. 2. 3.]


In [12]:
# ndarray from tuple 
x = (1,2,3)
a=np.asarray(x)
print(a)

[1 2 3]


In [14]:
# ndarray from list of tuples 
x = [(1,2,3),(4,5)]
b=np.asarray(x)
print(b)

[(1, 2, 3) (4, 5)]


### numpy.frombuffer
numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)

In [34]:
import numpy as np 
# s = b'hello world' 
a = np.frombuffer(s, dtype = 'S1',count=-1,offset=0) 
print (a)

[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']


In [38]:
# frombuffer alternative is fromstring
# let see the usage here
s='Hello Buddy'
a=np.fromstring(s,dtype='S1')
print(a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'B' b'u' b'd' b'd' b'y']


C:\Users\gajanana_ganjigatti\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:4: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  after removing the cwd from sys.path.


## Range Function

In [41]:
a=range(10)
print(a)

range(0, 10)


In [42]:
# Iter call
it=iter(a)
print(it)

In [43]:
# Fromiter 
b=np.fromiter(it,dtype=float)
print(b)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## NumPy - Array From Numerical Ranges

### numpy.arange
numpy.arange(start, stop, step, dtype)

In [44]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [46]:
# now set dtype=float
a=np.arange(10, dtype=float)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [48]:
# Set start and end parameters, step and dtype
a=np.arange(2,20,3,dtype=float)
print(a)

[ 2.  5.  8. 11. 14. 17.]
