In [2]:
import numpy as np

In [3]:
a=np.arange(10)

In [5]:
# slice(start,stop,step)
s=slice(2,7,2)
print(s)

slice(2, 7, 2)


In [6]:
print(a[s])

[2 4 6]


In [7]:
# above can be represented with :
a=np.arange(10)
b=a[2:7:2]
print(b)

[2 4 6]


In [8]:
# Slicing single item
b=a[5]
print(b)

5


In [9]:
# Slicing from the start of the index
b=a[2:]
print(b)

[2 3 4 5 6 7 8 9]


In [10]:
# Now slice between the indexes
b=a[1:4]
print(b)

[1 2 3]


#### MultiDimensional array

In [11]:
a=np.array([[1,2,3],[3,4,5],[5,6,7]])
print(a)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [12]:
# Now slice from starting of the index
b=a[1:]
print(b)

[[3 4 5]
 [5 6 7]]


In [13]:
# Lets define the array again 
a=np.array([[9,8,7],[6,5,4],[3,2,1]])
print(a)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [14]:
# Return only second column
b=a[...,1]
print(b)

[8 5 2]


In [15]:
# Return all the second row
b=a[1,...]
print(b)

[6 5 4]


In [16]:
# return from colum onwards
b=a[...,1:]
print(b)

[[8 7]
 [5 4]
 [2 1]]
