In [1]:
import numpy as np

In [2]:
a=np.array([[1,2],[3,4],[5,6]])

In [4]:
b=a[[0,1,2],[0,1,0]]
print('array a:\n',a)
print('array b:\n',b)

array a:
 [[1 2]
 [3 4]
 [5 6]]
array b:
 [1 4 5]


 #### [[1 2]  
 #### [3 4]  
 #### [5 6]]
 
  ####  value [1 2] are in position [(0,0)(0,1)]
  ####  value [3 4] are in position [(1,0)(1,1)]
  ####  value [5 6] are in position [(2,0)(2,1)]
 
  ####  When b=a[[0,1,2],
   ####                  [0,1,0]]
 #### values of b for location in a are [(0,0)]=1
 ####                                                       [(1,1)]=4
  ####                                                     [(2,0)]=5

In [5]:
a=np.array([[10,9,8],[7,6,5],[4,3,2],[1,11,12]])
print('Array a:\n', a)

Array a:
 [[10  9  8]
 [ 7  6  5]
 [ 4  3  2]
 [ 1 11 12]]


In [6]:
# Slicing 
b=a[1:4,1:3]
print(b)

[[ 6  5]
 [ 3  2]
 [11 12]]


In [9]:
# Advanced slicing as below
b=a[1:4,[1,2]]
print(b)

[[ 6  5]
 [ 3  2]
 [11 12]]


In [10]:
# print the value greater than 5
b=a[a>5]
print(b)

[10  9  8  7  6 11 12]
