In [1]:
import numpy as np

In [3]:
# print value from 0 to 60 step value = 5
a=np.arange(0,60,5)
print('a\n:',a)

a
: [ 0  5 10 15 20 25 30 35 40 45 50 55]


In [4]:
a=a.reshape(3,4)
print('reshaped a:\n',a)

reshaped a:
 [[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


In [5]:
# iteration using nditer
for i in np.nditer(a):
    print(i)

0
5
10
15
20
25
30
35
40
45
50
55


In [7]:
# iterating over transpore of the above array
b=a.T
print('Transpose of origina array a:\n',b)

Transpose of origina array a:
 [[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


In [8]:
# iteration using nditer
for j in np.nditer(b):
    print(j)

0
5
10
15
20
25
30
35
40
45
50
55


In [9]:
# Sorting F-style and C-style
# where F-style column iteration
# wher c-style row iteration
print('transpose b:\n',b)

transpose b:
 [[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


In [10]:
c=b.copy(order="C")
print('C-style order sorting:\n',c)
for i in np.nditer(c):
    print(i)

C-style order sorting:
 [[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
20
40
5
25
45
10
30
50
15
35
55


In [11]:
d=b.copy(order="F")
print("F-style order sorting:\n",d)
for j in np.nditer(d):
    print(j)

F-style order sorting:
 [[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
5
10
15
20
25
30
35
40
45
50
55


In [12]:
# Forcing nditer to follow C -style or F- Style
print('Array a:\n',a)
print("C-style sorted:\n")
for i in np.nditer(a,order='C'):
    print(i)

Array a:
 [[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
C-style sorted:

0
5
10
15
20
25
30
35
40
45
50
55


In [13]:
print("F-style sorted:\n")
for j in np.nditer(a,order='F'):
    print(j)

F-style sorted:

0
20
40
5
25
45
10
30
50
15
35
55


#### Broadcasting Iteration

In [14]:
print("original Array: a\n",a)

original Array: a
 [[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


In [15]:
print("Define another array")
b=np.array([1,2,3,4],dtype=int)
print(b)

Define another array
[1 2 3 4]


In [39]:
# Now modification using array b
for i,j in np.nditer((a,b)):
    print ("%d:%d" %(i,j))
    if(j==4):
        print("\n")

0:1
5:2
10:3
15:4


20:1
25:2
30:3
35:4


40:1
45:2
50:3
55:4


