In [1]:
import numpy as np

In [2]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


## 1. Changing Shape

### 1.1 numpy.reshape

In [3]:
b=a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [5]:
b=a.reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]


### 1.2 numpy.ndarray.flat

In [6]:
c=np.arange(10).reshape(5,2)
print(c)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [7]:
print('now flat this:')
d=c.flat[6]
print(d)

now flatten this:
6


In [11]:
print('Default is column major, order="c"')
print(c.flatten())

Default is column major, order="c"
[0 1 2 3 4 5 6 7 8 9]


In [12]:
print('F-style ordering:\n',c.flatten(order='F'))

F-style ordering:
 [0 2 4 6 8 1 3 5 7 9]


### 1.3 numpy.ravel

In [14]:
print('original array a: \n', c)

original array a: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [15]:
print('After applyin ravel function: \n',c.ravel())

After applyin ravel function: 
 [0 1 2 3 4 5 6 7 8 9]


In [16]:
print('After applyin ravel function with F-style: \n',c.ravel(order='F'))

After applyin ravel function with F-style: 
 [0 2 4 6 8 1 3 5 7 9]


## 2. Transpose Operations

### 2.1 numpy.transpose

In [17]:
d=np.arange(12).reshape(3,4)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [20]:
# now transpose this
e=np.transpose(d)
print(e)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### 2.2 numpy.ndarray.T

In [24]:
z=np.arange(20).reshape(10,2)
print(z)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [25]:
y=z.T
print(y)

[[ 0  2  4  6  8 10 12 14 16 18]
 [ 1  3  5  7  9 11 13 15 17 19]]


## 3. numpy.rollaxis

### 3.1 numpy.rollaxis(arr, axis, start)

In [29]:
a=np.arange(8).reshape(2,2,2)
print(a)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [30]:
# to roll axis-2 to axis-0 (along width to along depth) 
print ('After applying rollaxis function:',np.rollaxis(a,2))

After applying rollaxis function: [[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]


In [31]:
print ('After applying rollaxis function:',np.rollaxis(a,2,1) )

After applying rollaxis function: [[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]


## 4. numpy.swapaxes

### 4.1 numpy.swapaxes(arr, axis1, axis2)

In [34]:
a = np.arange(24).reshape(2,4,3) 
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [35]:
# now swap numbers between axis 0 (along depth) and axis 2 (along width) 
print ('The array after applying the swapaxes function:',np.swapaxes(a,0,2))

The array after applying the swapaxes function: [[[ 0 12]
  [ 3 15]
  [ 6 18]
  [ 9 21]]

 [[ 1 13]
  [ 4 16]
  [ 7 19]
  [10 22]]

 [[ 2 14]
  [ 5 17]
  [ 8 20]
  [11 23]]]


## 5. Changing Dimensions

### 5.1 numpy.broadcast

In [36]:
import numpy as np

In [37]:
a = np.array([[1], [2], [3]]) 
b = np.array([4, 5, 6])  

In [40]:
print("a:\n",a)
print("b:\n",b)

a:
 [[1]
 [2]
 [3]]
b:
 [4 5 6]


In [41]:
c=np.broadcast(a,b)
print(c)

In [44]:
print('Broadcast a and b')
d,e = c.iters 
print (next(d), next(e)) 
print (next(d), next(e))
print('\n')

Broadcast a and b
1 4
1 5




In [46]:
print ('The shape of the broadcast object:' ,c.shape)

The shape of the broadcast object: (3, 3)


In [1]:
import numpy as np

### 5.2 numpy.expand_dims
    numpy.expand_dims(arr, axis)
    arr--> Array
    axis--> Position where new axis to be inserted

In [2]:
a=np.array(([1,2],[3,4]))

In [4]:
print("Array a:\n ",a)

Array a:
  [[1 2]
 [3 4]]


In [5]:
b=np.expand_dims(a,axis=0)
print("Array b:\n",b)

Array b:
 [[[1 2]
  [3 4]]]


In [10]:
print("Shape of a: %d\n and \nshape of b: %d\n",a.shape,b.shape)

Shape of a: %d
 and 
shape of b: %d
 (2, 2) (1, 2, 2)


In [11]:
print('now insert at axis=1 location')
b=np.expand_dims(a,axis=1)
print("Array b:\n",b)

now insert at axis=1 location
Array b:
 [[[1 2]]

 [[3 4]]]


In [12]:
print("shape of b:",b.shape)

shape of b: (2, 1, 2)


In [14]:
print('lets find out the dimension of a & b:\n')
print('a dim: ',a.ndim,' b dim: ',b.ndim)

lets find out the dimension of a & b:

a dim:  2  b dim:  3


### 5.3 numpy.squeeze
    numpy.squeeze(arr, axis)
    arr--> Array
    axia--> int or tuple of int. selects a subset of single dimensional entries in the shape

In [26]:
a=np.arange(12).reshape(1,6,2)
print("Array a: \n",a)
print('Array a shape: ',a.shape)
print('Array a dim: ',a.ndim)

Array a: 
 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]]]
Array a shape:  (1, 6, 2)
Array a dim:  3


In [27]:
print('now call squeeze method:')
b=np.squeeze(a)
print('Array b: \n',b)
print('Array b shape: ',b.shape)
print('Array b dim: ',b.ndim)

now call squeeze method:
Array b: 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
Array b shape:  (6, 2)
Array b dim:  2


## 6. Joining Arrays

### 6.1 numpy.concatenate
    Joining two or more arrays with same shape and specified axis defined. 
    numpy.concatenate((a1, a2, ...an), axis)
    a1,a2..an-->Arrays
    axis-->Default 0, to which axis to be joined

In [33]:
import numpy as np
a=np.array([[1,2],[3,4],[10,12]])
print('Array a:\n',a)
print('Array a Shape: ',a.shape)
print('Array a dimension: ',a.ndim)

Array a:
 [[ 1  2]
 [ 3  4]
 [10 12]]
Array a Shape:  (3, 2)
Array a dimension:  2


In [34]:
print('now define another array b:')
b=np.array([[12,34],[32,45],[77,89]])
print('Array b: \n',b)
print('Array b shape: ',b.shape)
print('Array b dimension: ',b.ndim)

now define another array b:
Array b: 
 [[12 34]
 [32 45]
 [77 89]]
Array b shape:  (3, 2)
Array b dimension:  2


In [36]:
print('now joining array a and b to axis=0')
c=np.concatenate((a,b))
print('Array c Concatenate:\n',c)
print('Array c shape: ',c.shape)
print('Array c dimension: ',c.ndim)

now joining array a and b to axis=0
Array c Concatenate:
 [[ 1  2]
 [ 3  4]
 [10 12]
 [12 34]
 [32 45]
 [77 89]]
Array c shape:  (6, 2)
Array c dimension:  2


In [37]:
print('now joining array a and b to axis=1')
d=np.concatenate((a,b),axis=1)
print('Array d: \n',d)
print('Array d shape: ',d.shape)
print('Array d dimension: ',d.ndim)

now joining array a and b to axis=1
Array d: 
 [[ 1  2 12 34]
 [ 3  4 32 45]
 [10 12 77 89]]
Array d shape:  (3, 4)
Array d dimension:  2


In [41]:
print('now joining array a and b to axis=2')
f=np.concatenate((a,b),axis=1)
print('Array f: \n',d)
print('Array f shape: ',f.shape)
print('Array f dimension: ',f.ndim)

now joining array a and b to axis=2
Array f: 
 [[ 1  2 12 34]
 [ 3  4 32 45]
 [10 12 77 89]]
Array f shape:  (3, 4)
Array f dimension:  2


### 6.2 numpy.stack
    Joine to new axis defined
    numpy.stack(arrays, axis)

In [50]:
import numpy as np
a=np.array([[9,5],[3,6]])
print('Array a:\n',a)
print('Array a shape: ',a.shape)
print('Array a dimension: ',a.ndim)

Array a:
 [[9 5]
 [3 6]]
Array a shape:  (2, 2)
Array a dimension:  2


In [52]:
b=np.array([[1,8],[0,4]])
print('Array b: \n',b)
print('Array b shpae: ',b.shape)
print('Array b dimension: ',b.ndim)

Array b: 
 [[1 8]
 [0 4]]
Array b shpae:  (2, 2)
Array b dimension:  2


In [53]:
print('now stack array a and b to axis=0')
c=np.stack((a,b),0)
print('Array c:\n',c)
print('Array c shape: ',c.shape)
print('Array c dimension: ',c.ndim)

now stack array a and b to axis=0
Array c:
 [[[9 5]
  [3 6]]

 [[1 8]
  [0 4]]]
Array c shape:  (2, 2, 2)
Array c dimension:  3


In [54]:
print('now stack array a and b to axis=1')
d=np.stack((a,b),1)
print('Array d:\n',d)
print('Array d shape: ',d.shape)
print('Array d dimension: ',d.ndim)

now stack array a and b to axis=1
Array d:
 [[[9 5]
  [1 8]]

 [[3 6]
  [0 4]]]
Array d shape:  (2, 2, 2)
Array d dimension:  3


### 6.3 numpy.hstack
    Make single array horizantal

In [55]:
a=np.array([[1,4],[7,9],[2,3]])
print('Array a:\n',a)
print('Array a shape: ',a.shape)
print('Array a dimension: ',a.ndim)

Array a:
 [[1 4]
 [7 9]
 [2 3]]
Array a shape:  (3, 2)
Array a dimension:  2


In [56]:
b=np.array([[1,8],[0,14],[11,17]])
print('Array b: \n',b)
print('Array b shpae: ',b.shape)
print('Array b dimension: ',b.ndim)

Array b: 
 [[ 1  8]
 [ 0 14]
 [11 17]]
Array b shpae:  (3, 2)
Array b dimension:  2


In [59]:
c=np.hstack((a,b))
print('Array Horizontal stacking c:\n',c)
print('Array c shape: ',c.shape)
print('Array c dimension: ',c.ndim)

Array Horizontal stacking c:
 [[ 1  4  1  8]
 [ 7  9  0 14]
 [ 2  3 11 17]]
Array c shape:  (3, 4)
Array c dimension:  2


### 6.4 numpy.vstack
    Make single array vertical

In [60]:
a=np.array([[1,4],[7,9],[2,3]])
print('Array a:\n',a)
print('Array a shape: ',a.shape)
print('Array a dimension: ',a.ndim)

Array a:
 [[1 4]
 [7 9]
 [2 3]]
Array a shape:  (3, 2)
Array a dimension:  2


In [61]:
b=np.array([[1,8],[0,14],[11,17]])
print('Array b: \n',b)
print('Array b shpae: ',b.shape)
print('Array b dimension: ',b.ndim)

Array b: 
 [[ 1  8]
 [ 0 14]
 [11 17]]
Array b shpae:  (3, 2)
Array b dimension:  2


In [62]:
c=np.vstack((a,b))
print('Array vertical stacking c:\n',c)
print('Array c shape: ',c.shape)
print('Array c dimension: ',c.ndim)

Array vertical stacking c:
 [[ 1  4]
 [ 7  9]
 [ 2  3]
 [ 1  8]
 [ 0 14]
 [11 17]]
Array c shape:  (6, 2)
Array c dimension:  2


## 7 Splitting Arrays

### 7.1 numpy.split
    Split array into subarrays for defined axis

In [64]:
a=np.arange(16)
print('Array a:\n',a)
print('Array a shape: ',a.shape)
print('Array a dimension: ',a.ndim)

Array a:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Array a shape:  (16,)
Array a dimension:  1


In [67]:
b=np.split(a,4)
print('Array b splited in 4 equal size \n',b)

Array b: 
 [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11]), array([12, 13, 14, 15])]


In [69]:
print('now split at position defined')
c=np.split(a,[7,10])
print('Array b splited at position [7,10]:  \n',c)

now split at position defined
Array b splited at position [7,10]:  
 [array([0, 1, 2, 3, 4, 5, 6]), array([7, 8, 9]), array([10, 11, 12, 13, 14, 15])]


In [79]:
print('now split at axis=1 defined')
f=np.split(a,8,0)
print('Array b split at axis=1 defined:  \n',f)

now split at axis=1 defined
Array b split at axis=1 defined:  
 [array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9]), array([10, 11]), array([12, 13]), array([14, 15])]


### 7.2 numpy.hsplit
     column wise split

In [84]:
a=np.arange(64).reshape(8,8)
print('Array a:\n',a)
print('Array a shape: ',a.shape)
print('Array a dimension: ',a.ndim)

Array a:
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
Array a shape:  (8, 8)
Array a dimension:  2


In [87]:
b = np.hsplit(a,4)
print('Array b horizantal split:  \n',b)

Array b horizantal split:  
 [array([[ 0,  1],
       [ 8,  9],
       [16, 17],
       [24, 25],
       [32, 33],
       [40, 41],
       [48, 49],
       [56, 57]]), array([[ 2,  3],
       [10, 11],
       [18, 19],
       [26, 27],
       [34, 35],
       [42, 43],
       [50, 51],
       [58, 59]]), array([[ 4,  5],
       [12, 13],
       [20, 21],
       [28, 29],
       [36, 37],
       [44, 45],
       [52, 53],
       [60, 61]]), array([[ 6,  7],
       [14, 15],
       [22, 23],
       [30, 31],
       [38, 39],
       [46, 47],
       [54, 55],
       [62, 63]])]


### 7.2 numpy.vsplit
     row wise split

In [88]:
c = np.vsplit(a,4)
print('Array c vertical split:  \n',c)

Array c vertical split:  
 [array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]]), array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]]), array([[32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]]), array([[48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])]


## 8 Adding / Removing Elements

### 8.1 numpy.resize

In [90]:
f=np.resize(a,(3,2))
print('Array a shape: ',a.shape)
print('Resized array f: \n',f)

Array a shape:  (8, 8)
Resized array f: 
 [[0 1]
 [2 3]
 [4 5]]


In [91]:
print('Array a: \n',a)

Array a: 
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]


In [93]:
print('now resize to higher size:')
g=np.resize(a,(9,10))
print('Array a shape: ',a.shape)
print('Resized array g: \n',g)

now resize to higher size:
Array a shape:  (8, 8)
Resized array g: 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63  0  1  2  3  4  5]
 [ 6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25]]


In [94]:
print('Array g shape: ',g.shape)

Array g shape:  (9, 10)


### 8.2 numpy.append
    Dimension alway has to match 
    we can specify the axis location to append

In [96]:
a=np.array([[1,2,3],[4,5,6]])
print('Array a:\n',a)
print('Array a shape: ',a.shape)
print('Array a dimension: ',a.ndim)

Array a:
 [[1 2 3]
 [4 5 6]]
Array a shape:  (2, 3)
Array a dimension:  2


In [97]:
print('now append [9,8,7]')
b=np.append(a,[9,8,7])
print('Array b: \n',b)
print('Array b shpae: ',b.shape)
print('Array b dimension: ',b.ndim)

now append [9,8,7]
Array b: 
 [1 2 3 4 5 6 9 8 7]
Array b shpae:  (9,)
Array b dimension:  1


In [99]:
print('now append [9,8,7] to axis=0')
b=np.append(a,[[9,8,7]],axis=0)
print('Array b: \n',b)
print('Array b shpae: ',b.shape)
print('Array b dimension: ',b.ndim)

now append [9,8,7] to axis=0
Array b: 
 [[1 2 3]
 [4 5 6]
 [9 8 7]]
Array b shpae:  (3, 3)
Array b dimension:  2


In [102]:
print('now append [[9,8,7],[1,4,8]] to axis=1')
b=np.append(a,[[9,8,7],[1,4,8]],axis=1)
print('Array b: \n',b)
print('Array b shpae: ',b.shape)
print('Array b dimension: ',b.ndim)

now append [[9,8,7],[1,4,8]] to axis=1
Array b: 
 [[1 2 3 9 8 7]
 [4 5 6 1 4 8]]
Array b shpae:  (2, 6)
Array b dimension:  2


In [103]:
print('now append [[9,8,7],[1,4,8]] to axis=2')
b=np.append(a,[[9,8,7],[1,4,8],[9,9,0]],axis=2)
print('Array b: \n',b)
print('Array b shpae: ',b.shape)
print('Array b dimension: ',b.ndim)

now append [[9,8,7],[1,4,8]] to axis=2


AxisError: axis 2 is out of bounds for array of dimension 2

 #### what i understood from above error is that alway ndime alway greater tha axis value.
 
 #### below example explains more on this

In [105]:
a=np.arange(12).reshape(2,3,2)
print('Array a:\n',a)
print('Array a shape: ',a.shape)
print('Array a dimension: ',a.ndim)

Array a:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
Array a shape:  (2, 3, 2)
Array a dimension:  3


In [116]:
b=np.append(a,[[[9,8],[1,4],[9,9]],[[9,8],[1,4],[9,9]]],axis=2)
print('Array b: \n',b)
print('Array b shpae: ',b.shape)
print('Array b dimension: ',b.ndim)

Array b: 
 [[[ 0  1  9  8]
  [ 2  3  1  4]
  [ 4  5  9  9]]

 [[ 6  7  9  8]
  [ 8  9  1  4]
  [10 11  9  9]]]
Array b shpae:  (2, 3, 4)
Array b dimension:  3


### 8.3 numpy.insert
    numpy.insert(arr, obj, values, axis)
    arr-->Array
    obj--> Index location insertion made
    values--> Values to inserted to index location
    axis--> axis defined for insertion

In [117]:
a = np.array([[1,2],[3,4],[5,6]]) 

In [118]:
print('Initial Array a: \n',a)

Initial Array a: 
 [[1 2]
 [3 4]
 [5 6]]


In [120]:
print('if axis parameter not passed then it will flattened and inserted to index location')
b=np.insert(a,5,[9,10])
print('After inserting to array b:\n',b)

if axis parameter not passed then it will flattened and inserted to index location
After inserting to array b:
 [ 1  2  3  4  5  9 10  6]


In [123]:
print('axis=0 then')
b=np.insert(a,1,[19,99],axis=0)
print('After inserting to array b at axis=0:\n',b)

axis=0 then
After inserting to array b at axis=0:
 [[ 1  2]
 [19 99]
 [ 3  4]
 [ 5  6]]


In [125]:
print('axis=1 then')
b=np.insert(a,1,99,axis=1)
print('After inserting to array b at axis=0:\n',b)

axis=1 then
After inserting to array b at axis=0:
 [[ 1 99  2]
 [ 3 99  4]
 [ 5 99  6]]


### 8.4 numpy.delete

In [126]:
a=np.arange(24).reshape(4,6)
print('Initial array a:\n',a)

Initial array a:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [128]:
print('if axis parameter not passed then it will flattened and deleted from the index location')
b=np.delete(a,15)
print('After deleting from array b:\n',b)

if axis parameter not passed then it will flattened and deleted from the index location
After deleting from array b:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 16 17 18 19 20 21 22 23]


In [129]:
print('now delete from particular row')
b=np.delete(a,3,axis=0)
print('After deleting column from array b:\n',b)

now delete from particular row
After deleting column from array b:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [130]:
print('now delete from particular row at axis=1')
b=np.delete(a,3,axis=1)
print('After deleting column from array b:\n',b)

now delete from particular row at axis=1
After deleting column from array b:
 [[ 0  1  2  4  5]
 [ 6  7  8 10 11]
 [12 13 14 16 17]
 [18 19 20 22 23]]


In [134]:
print('delete alternative values(devisible by slice value defined) from array ')
b=np.delete(a,np.s_[::4])
print('After slicing b: \n',b)
print('dont see 4,8,16')

delete alternative values(devisible by slice value defined) from array 
After slicing b: 
 [ 1  2  3  5  6  7  9 10 11 13 14 15 17 18 19 21 22 23]
dont see 4,8,16


### 8.5 numpy.unique
    numpy.unique(arr, return_index, return_inverse, return_counts)
    arr--> Array
    return_index--> If True, returns the indices of elements in the input array
    return_inverse--> If True, returns the indices of unique array, which can be used to reconstruct the input array
    return_count --> If True, returns the number of times the element in unique array appears in the original array

In [135]:
import numpy as np 
a = np.array([5,2,6,2,7,5,2,3,1,6,8,2,9,9,0,]) 
print('Initial Array a:\n',a)

Initial Array a:
 [5 2 6 2 7 5 2 3 1 6 8 2 9 9 0]


In [136]:
print('unique values of the initial array:\n',np.unique(a))

unique values of the initial array:
 [0 1 2 3 5 6 7 8 9]


In [137]:
uniq, indices=np.unique(a,return_index=True)
print('unique array indices: \n',indices)

unique array indices: 
 [14  8  1  7  0  2  4 10 12]


In [140]:
uniq, indices=np.unique(a,return_inverse=True)
print('indices of unique array : \n',uniq)
print('indices   : \n',indices)

indices of unique array : 
 [0 1 2 3 5 6 7 8 9]
indices   : 
 [4 2 5 2 6 4 2 3 1 5 7 2 8 8 0]


In [141]:
print('reconstruct original index: \n',uniq[indices])

reconstruct original index: 
 [5 2 6 2 7 5 2 3 1 6 8 2 9 9 0]


In [143]:
uniq,indices = np.unique(a,return_counts = True) 
print ('Return the count of repetitions of unique elements:' )
print(uniq)
print('\n')
print(indices)

Return the count of repetitions of unique elements:
[0 1 2 3 5 6 7 8 9]


[1 1 4 1 2 2 1 1 2]
